apiVersion: eks.amazonaws.com/v1
kind: TargetGroupBinding
metadata:
  name: kd-portal
spec:
  serviceRef:
    name: kd-portal
    port: 3000
  targetType: ip
  targetGroupARN: arn:aws:elasticloadbalancing:ap-southeast-1:767397910274:targetgroup/kd-portal-tg-dev2/a4f504fc14b5a319
